### ISSUE TITLE
Reuse generated by Nuxt Webpack config

### ISSUE THREAD

**Issue by Koc** [mstrlaw/nuxt-storybook#1]
For now for Storybook run Webpack config creates from scratch https://github.com/mstrlaw/nuxt-storybook/blob/master/.storybook/webpack.config.js . It hasn't sense, because Nuxt generates config for us based on `nuxt.config.js`.

Also Tailwind 1.0 was released.

**Comment by Koc** [comment]
See https://github.com/nuxt/nuxt.js/issues/4286 for technical direction for that.

**Comment by mstrlaw** [comment]
Thanks for pointing that out @Koc! I thought there'd be a way of reusing Nuxt's config but was too lazy to look into it back then.

**Comment by Anima-t3d** [comment]
Also see: https://nuxtjs.org/faq/extend-webpack/
