### ISSUE TITLE
Yarn dev issue

### ISSUE THREAD

**Issue by szafran89** [mstrlaw/nuxt-storybook#2]
There is an issue once I run `yarn dev`

![image](https://user-images.githubusercontent.com/5370251/66828956-9654b000-ef52-11e9-9daf-0c9cf688d35e.png)

Do you know how to solve it?

**Comment by usulix** [comment]
That's a current nuxt thing. core-js is at version 3, but nuxt requires version 2
to package.json, under dependencies add
`"core-js": "^2.0.0",` 
so it looks like
` "dependencies": {
    "@nuxtjs/axios": "^5.6.0",
    "@nuxtjs/dotenv": "^1.4.1",
    "core-js": "^2.0.0",
    "nuxt": "^2.9.2"
  },`
and run npm install again
